name: Build project using muddler and upload artifact

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3.3.0
      
      - name: Build With Muddler
        # You may pin to the exact commit or the version.
        # uses: demonnic/build-with-muddler@a9355b3c4f93553287e0f2d4087508b9f6164225
        uses: demonnic/build-with-muddler@v1.4
        with:
          # Version of muddler to use
          muddlerVersion: LATEST # optional, default is LATEST
          # What directory to run muddler in.
          #workingDir: # optional, default is ${{ github.workspace }}

      #- name: Upload Artifact
      #  # https://github.com/marketplace/actions/upload-a-build-artifact#using-outputs
      #  uses: actions/upload-artifact@v4.3.3
      #  with:
      #    name: MUDKIP_Mud2
      #    path: build/tmp/

      #- uses: actions/download-artifact@v4
      #  # https://github.com/marketplace/actions/download-a-build-artifact
      #  with:
      #    merge-multiple: true
          
      - name: JSON to variables
        # see https://github.com/antifree/json-to-variables
        # You may pin to the exact commit or the version.
        # uses: antifree/json-to-variables@cc8c6394031e145c90f7f9ec909d83df92431fb8
        uses: antifree/json-to-variables@v1.2.0
        with:
          # The json file.
          filename: "./release.json"
          # The prefix for variables.
          prefix: "mfile"

      - uses: ncipollo/release-action@v1
        # see https://github.com/marketplace/actions/create-release
        with:
          artifacts: "build/MUDKIP_Mud2.*,release.json"
          allowUpdates: true
          bodyFile: "./README.md"
          tag: ${{ env.mfile_version }}
